[package]
name = "typstdoc-core"
description = "Compiles Typst fragments from Rust doc comments to HTML"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["embedded-fonts"]
embedded-fonts = ["typst-assets/fonts"]

[dependencies]
dirs = "6.0.0"
pulldown-cmark = { version = "0.13.4", default-features = false }
typst = "0.15.1"
typst-assets = "0.15.1"
typst-html = "0.15.1"
